In [16]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer

In [17]:
df=pd.read_csv("dataset/synthetic_logs.csv")

In [18]:
df.head()

,timestamp,source,log_message,target_label
0,27-06-2025 07:20,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert
3,12-07-2025 00:24,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status
4,02-06-2025 18:25,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status

In [19]:
df.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI', 'LegacyCRM'], dtype=object)

In [20]:
df.target_label.unique()

array(['HTTP Status', 'Critical Error', 'Security Alert', 'Error',
       'System Notification', 'Resource Usage', 'User Action',
       'Workflow Error', 'Deprecation Warning'], dtype=object)

In [21]:
df[df.source=="LegacyCRM"]

,timestamp,source,log_message,target_label
60,06-10-2025 16:55,LegacyCRM,Lead conversion failed for prospect ID 7842 du...,Workflow Error
255,03-05-2025 16:55,LegacyCRM,API endpoint 'getCustomerDetails' is deprecate...,Deprecation Warning
377,24-06-2025 12:16,LegacyCRM,Customer follow-up process for lead ID 5621 fa...,Workflow Error
1325,17-04-2025 07:33,LegacyCRM,Escalation rule execution failed for ticket ID...,Workflow Error
1734,30-04-2025 07:47,LegacyCRM,The 'ExportToCSV' feature is outdated. Please ...,Deprecation Warning
1826,23-01-2025 10:33,LegacyCRM,Support for legacy authentication methods will...,Deprecation Warning
2217,12-05-2025 09:46,LegacyCRM,Task assignment for TeamID 3425 could not comp...,Workflow Error

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2410 entries, 0 to 2409
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   timestamp     2410 non-null   object
 1   source        2410 non-null   object
 2   log_message   2410 non-null   object
 3   target_label  2410 non-null   object
dtypes: object(4)
memory usage: 75.4+ KB

In [23]:
df.describe()

,timestamp,source,log_message,target_label
count,2410,2410,2410,2410
unique,2403,6,2265,9
top,30-08-2025 19:35,ThirdPartyAPI,Backup completed successfully.,HTTP Status
freq,2,496,60,1017

<h2>Embeddings</h2>

In [25]:
model = SentenceTransformer('all-MiniLM-L6-v2')
embeddings = model.encode(df["log_message"].tolist())
embeddings[:2]

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

C:\Users\Dhanj\anaconda3\envs\log_classif\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Dhanj\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

array([[-1.02939621e-01,  3.35459411e-02, -2.20260732e-02,
         1.55101740e-03, -9.86917876e-03, -1.78956270e-01,
        -6.34409785e-02, -6.01761639e-02,  2.81109158e-02,
         5.99620491e-02, -1.72618348e-02,  1.43363548e-03,
        -1.49560034e-01,  3.15287686e-03, -5.66030927e-02,
         2.71685235e-02, -1.49891041e-02, -3.54037657e-02,
        -3.62936445e-02, -1.45410765e-02, -5.61491773e-03,
         8.75539035e-02,  4.55120578e-02,  2.50963885e-02,
         1.00187510e-02,  1.24267349e-02, -1.39923573e-01,
         7.68696293e-02,  3.14095505e-02, -4.15247958e-03,
         4.36902344e-02,  1.71250012e-02, -8.00951198e-02,
         5.74006326e-02,  1.89091656e-02,  8.55262503e-02,
         3.96398641e-02, -1.34371817e-01, -1.44360063e-03,
         3.06704035e-03,  1.76854044e-01,  4.44885530e-03,
        -1.69274509e-02,  2.24266481e-02, -4.35049310e-02,
         6.09034160e-03, -9.98169929e-03, -6.23972900e-02,
         1.07372422e-02, -6.04895083e-03, -7.14660808e-02,
        -8.45799781e-03, -3.18019874e-02, -1.00518376e-01,
         2.25873096e-04, -1.89341009e-02, -3.17793973e-02,
         4.00860943e-02,  2.19178163e-02, -2.59528961e-02,
         5.84525056e-02, -8.12509581e-02,  2.12029163e-02,
        -5.02687655e-02,  1.32057499e-02,  1.32675481e-03,
         2.27062907e-02, -3.45793478e-02,  3.91546972e-02,
        -2.09433399e-02,  3.24829482e-03,  4.43961099e-02,
        -9.85357612e-02, -2.88895369e-02, -6.85023936e-03,
         5.38818911e-02,  6.46110177e-02, -2.45060585e-02,
         9.21828747e-02, -7.49868751e-02,  1.23994909e-02,
        -1.00026578e-01, -4.64910977e-02,  6.01570047e-02,
        -2.46480722e-02, -7.08076209e-02, -2.77270824e-02,
         9.72611383e-02,  3.85841392e-02, -1.44293057e-02,
        -7.46909878e-04, -1.04304878e-02, -1.61842871e-02,
         4.43628095e-02,  9.25995968e-03,  7.14165792e-02,
         6.37917742e-02,  4.94931564e-02, -6.02567680e-02,
         4.04805690e-02, -3.42860855e-02, -1.93881039e-02,
         6.61233589e-02,  6.01589568e-02,  1.09371776e-02,
        -5.38631296e-03,  1.44579662e-02,  9.25429910e-02,
        -3.14564183e-02, -1.84352025e-02,  9.91876610e-03,
        -1.85574219e-02,  1.31284434e-03,  2.26702014e-05,
         2.02741218e-03,  2.75256746e-02, -4.81928065e-02,
         5.42826168e-02, -7.32066929e-02,  4.88667302e-02,
         4.98490408e-02, -9.01139528e-03, -4.68905792e-02,
        -4.25887071e-02, -8.19523931e-02,  3.87106128e-02,
         7.85504058e-02,  1.46077081e-32,  1.66706275e-02,
         5.25494143e-02, -1.82448905e-02, -1.26686739e-02,
         6.52837083e-02, -2.11777352e-02, -4.06323038e-02,
         4.14947495e-02, -2.48360801e-02, -1.33068245e-02,
        -5.46753556e-02, -5.99200139e-04, -4.89246612e-03,
        -6.27359450e-02, -3.84878367e-02, -6.13543652e-02,
         8.27405825e-02,  2.34379973e-02, -8.63091834e-03,
         1.31003130e-02,  6.44215122e-02, -4.41361926e-02,
        -6.98633417e-02, -7.36059994e-02, -4.33264039e-02,
         6.96522417e-03, -5.05956709e-02, -1.60911996e-02,
        -5.66794015e-02,  3.35454731e-03,  5.34115247e-02,
         2.47761514e-02, -1.47986487e-02, -2.93242969e-02,
         7.30228499e-02, -1.86833944e-02,  8.13137367e-02,
        -2.69967224e-02, -5.68056367e-02, -6.59389049e-02,
        -5.95394848e-03,  2.85312776e-02, -7.85358176e-02,
        -2.76694540e-03, -3.26469471e-03, -9.28332806e-02,
        -7.27363005e-02, -3.31903026e-02,  1.01411112e-01,
         9.79882479e-02, -9.78740230e-02,  1.98667571e-02,
         2.38837320e-02, -1.81672648e-02, -3.73708978e-02,
         1.96551997e-03,  6.34425730e-02,  1.18271559e-02,
        -1.12041300e-02, -3.87316644e-02,  9.32424441e-02,
         4.26628767e-03, -1.66872628e-02, -6.87464401e-02,
         1.55119859e-02, -4.97755483e-02,  3.34493034e-02,
         8.00032541e-02,  2.12282464e-02,  1.34581864e-01,
        -2.30729766e-02,  5.53858802e-02,  3.07558421e-02,
        -2.93905940e-02,  2.31905375e-02, -9.34307799e-02,
         7.58034959e-02, -5.21208439e-03, -5.14523312e-02,
         3.32688726e-02,  3.67963351e-02, -1.06450235e-02,
         1.01634776e-02, -2.07651369e-02, -5.85519075e-02,
         4.79328595e-02,  2.13694703e-02,  8.76213461e-02,
         3.35494406e-03, -3.80336568e-02, -1.81205384e-02,
         6.87449984e-03,  5.15880026e-02, -4.75598909e-02,
        -6.12065606e-02, -1.45483574e-32,  4.12801234e-03,
         4.59641684e-03, -5.63900359e-02,  4.32465039e-03,
        -1.09439227e-03,  9.31954943e-03, -2.20269002e-02,
         5.79564497e-02, -1.44787477e-02,  4.64155786e-02,
         1.43542871e-01, -6.89756870e-02,  6.09631799e-02,
        -8.93743932e-02,  2.40919460e-02,  2.06010658e-02,
        -2.82415487e-02, -6.48315251e-02,  5.64795695e-02,
        -7.48336036e-03, -3.52058038e-02,  8.51060525e-02,
         1.30359633e-02,  2.02257764e-02, -1.44390641e-02,
        -4.63718511e-02,  1.77209619e-02,  1.59105826e-02,
        -9.51009318e-02, -3.54526863e-02,  2.08696295e-02,
         3.84389190e-03, -8.77918154e-02,  6.44575655e-02,
         1.44171156e-02,  3.84733523e-03,  4.70991470e-02,
         4.94661182e-02,  1.53862564e-02, -2.59578805e-02,
         9.10894647e-02,  1.83307882e-02, -5.89206666e-02,
         2.51992680e-02, -3.30374353e-02,  8.23345333e-02,
         1.74792372e-02,  6.48047701e-02, -1.19674122e-02,
        -3.31778415e-02,  3.00177671e-02,  3.54220010e-02,
        -1.39624272e-02,  6.69272467e-02,  3.87919769e-02,
         6.06916696e-02,  1.17958151e-03, -2.38787029e-02,
        -1.26930416e-01,  1.13846380e-02,  1.59290042e-02,
        -1.29427500e-02, -8.63247886e-02,  8.53661261e-03,
         6.03761226e-02,  1.51121775e-02, -1.19132362e-01,
         1.15234600e-02,  5.97089604e-02, -3.93345878e-02,
         1.55673325e-02,  1.04602240e-02, -4.72456925e-02,
        -2.59243399e-02,  9.98525601e-03,  3.07146404e-02,
        -7.14844763e-02,  6.98965415e-03, -1.55133577e-02,
         2.18864139e-02, -2.78145913e-02,  6.92733005e-02,
        -2.75903586e-02,  2.62429845e-02,  3.52561660e-02,
        -4.26419862e-02,  7.46284146e-04,  6.59866631e-02,
        -5.15105948e-02, -3.58434319e-02, -6.53440924e-03,
        -2.75858175e-02, -1.00125581e-01,  7.83326104e-02,
        -1.45798642e-02, -6.18457250e-08,  2.00325698e-02,
         6.59784526e-02, -2.04702560e-02,  1.64043903e-02,
         7.63001442e-02,  7.32182562e-02,  5.65784518e-03,
        -6.97782438e-04, -3.63794621e-03,  6.02393858e-02,
        -3.27187181e-02, -6.45838156e-02, -5.97952493e-02,
        -1.76696330e-02,  6.10143691e-03, -5.63488016e-03,
        -1.22972250e-01,  6.35818988e-02, -2.19432022e-02,
        -1.16406500e-01,  2.34366246e-02, -7.23525658e-02,
         2.31773835e-02, -6.55987561e-02, -7.42682368e-02,
         2.60146223e-02,  3.59758623e-02,  7.68432692e-02,
        -3.08057331e-02, -2.34794039e-02, -6.30426034e-02,
        -3.62158157e-02, -1.03560016e-02, -4.75602485e-02,
        -2.87522227e-02,  2.96400599e-02, -5.26892208e-03,
         5.67889623e-02, -3.74485948e-03,  3.09612993e-02,
         3.48226950e-02,  3.78607921e-02,  2.10155267e-02,
         2.70691738e-02,  5.25520407e-02,  7.16229230e-02,
        -5.53755183e-03,  4.01093923e-02,  5.16276695e-02,
        -2.67314408e-02,  5.94224073e-02, -4.29224260e-02,
        -1.19760446e-02,  3.05984747e-02, -7.40331411e-02,
         1.84222143e-02, -8.64861440e-03, -8.83557573e-02,
        -5.91984391e-02, -1.00920675e-04,  1.12913631e-01,
         4.57792636e-03, -4.25971746e-02,  3.22620897e-03],
       [ 8.04571714e-03, -3.57392281e-02,  4.93873917e-02,
        -7.19184149e-03,  6.17644750e-04, -9.05685052e-02,
         5.75594865e-02, -4.39446270e-02,  1.74751636e-02,
         5.21203242e-02, -4.62332033e-02,  2.49039363e-02,
         4.80811782e-02,  6.86636567e-02,  3.56146656e-02,
         3.00089642e-02,  2.61449497e-02, -9.05241296e-02,
        -8.02173615e-02,  5.04851192e-02, -7.90870488e-02,
        -1.76855002e-03, -2.48927530e-02,  9.02152434e-02,
         5.83698181e-03, -6.91070855e-02, -6.67966083e-02,
        -6.99113635e-03, -1.04565986e-01, -2.66473852e-02,
         3.05640064e-02,  2.02934369e-02,  2.25454886e-02,
        -4.22687922e-03,  1.11173484e-02,  6.78260773e-02,
         1.06073590e-02,  7.56636113e-02, -8.22777823e-02,
         8.45735706e-03, -6.97612464e-02, -4.21974584e-02,
        -1.05674397e-02,  2.23673340e-02,  5.64496815e-02,
         8.16500373e-03,  1.09344080e-01,  3.16564441e-02,
        -1.76923554e-02, -3.21071148e-02, -3.39975841e-02,
        -4.91802581e-04,  3.72874690e-03,  2.83771455e-02,
        -1.28521984e-02, -1.07933208e-03, -6.32418916e-02,
         6.89900741e-02,  1.77270379e-02, -5.20960055e-02,
         8.28307122e-03,  5.45032695e-02, -5.42099662e-02,
        -4.53333110e-02, -4.07494120e-02, -2.82698181e-02,
         1.23605840e-02, -2.13816017e-02, -2.36265361e-02,
         1.25317592e-02, -2.37170625e-02,  3.97411808e-02,
        -1.24362275e-01,  7.60625228e-02,  5.50834052e-02,
         8.28216746e-02,  2.97118574e-02, -1.84067208e-02,
        -1.96194761e-02,  5.54319136e-02, -3.49144414e-02,
        -4.14678007e-02, -3.37047353e-02,  7.31324479e-02,
         4.41836640e-02,  2.55246740e-02, -8.26408435e-03,
        -1.07322847e-02, -4.26243879e-02, -2.84964102e-03,
         7.38559514e-02,  2.27767937e-02,  7.15389557e-04,
         4.36012261e-02,  5.09079471e-02,  6.38482645e-02,
        -2.73155570e-02, -6.55021369e-02, -7.69265294e-02,
         3.55171151e-02,  9.60493386e-02,  2.18195524e-02,
         1.20154712e-02, -1.17863379e-02, -4.57923161e-03,
        -8.58035590e-03,  3.37150730e-02,  2.31918134e-02,
        -7.58325532e-02, -5.23879267e-02,  4.53934073e-02,
        -3.80785577e-02, -3.34904976e-02,  9.20353308e-02,
         2.87688691e-02, -3.33816931e-02, -1.95852900e-03,
        -3.04580055e-04, -1.70499235e-02,  2.85335984e-02,
        -8.81096572e-02, -4.02253456e-02, -4.00093347e-02,
        -1.03193149e-02, -2.51968466e-02,  2.14093029e-02,
         1.31045237e-01, -5.29632801e-34, -1.09651692e-01,
         1.29811568e-02,  5.92657691e-03,  4.73506227e-02,
        -8.60296935e-03, -3.67089324e-02,  3.05215158e-02,
         5.53066693e-02, -4.71985638e-02, -1.25118727e-02,
        -1.15366414e-01,  9.07998811e-03,  1.07346505e-01,
        -4.94734831e-02, -1.34290671e-02, -4.61562574e-02,
         2.45320704e-02,  9.45076440e-03,  2.04324219e-02,
        -3.99919078e-02, -4.67826128e-02,  2.21171696e-02,
        -4.58187200e-02, -8.13272968e-03, -7.65670184e-03,
         1.92284547e-02,  4.85845432e-02, -2.55903210e-02,
         1.61540357e-03, -1.37180369e-02,  9.67309345e-03,
         7.36417389e-03,  1.14088319e-02,  1.28853440e-01,
         7.71836052e-03,  7.06362650e-02,  2.54452135e-02,
         4.06523943e-02,  2.44039707e-02,  1.43777113e-02,
        -6.00932501e-02,  7.38180280e-02, -2.44701020e-02,
         8.98901448e-02,  3.17055243e-03,  1.01834454e-01,
         4.17742133e-02, -5.95177487e-02, -3.23181786e-02,
         3.80938761e-02,  1.21155363e-02, -4.07834165e-02,
         2.84823403e-02,  4.90988754e-02, -9.35704913e-03,
         6.50074109e-02,  7.23532140e-02, -1.67793669e-02,
        -8.22419021e-03, -1.61573216e-02,  5.96225485e-02,
        -3.36083770e-02,  2.12108567e-02, -6.06090687e-02,
         1.54377669e-01, -7.24146292e-02, -3.77272554e-02,
        -3.26890312e-02, -1.80383236e-03, -1.01960171e-02,
        -1.60677219e-03, -6.91846609e-02,  8.28444809e-02,
         9.88839418e-02,  3.45466356e-03, -9.90247875e-02,
        -3.52826901e-02, -7.13178515e-02, -4.96000238e-02,
        -3.43954526e-02, -8.13042149e-02,  4.81448062e-02,
         5.00683207e-03, -2.21499726e-02, -5.60056977e-02,
         1.00067444e-02, -3.59794199e-02,  1.06184311e-01,
        -4.54196744e-02,  7.16393143e-02, -2.36773062e-02,
         9.98143200e-03,  2.73602195e-02,  1.05985463e-01,
         4.60163429e-02,  9.59029178e-34, -1.12306982e-01,
         2.78912336e-02, -3.35900635e-02,  5.39242551e-02,
        -2.22291443e-02,  1.53769050e-02,  3.10411565e-02,
         3.39011066e-02,  7.43167326e-02,  3.42471153e-02,
        -3.35047860e-03, -2.05350518e-02, -3.62370051e-02,
         2.29334142e-02, -3.01992167e-02, -1.00819930e-01,
         3.29193994e-02,  6.77542835e-02,  1.35645578e-02,
        -5.20545896e-03, -6.58158809e-02,  9.54550654e-02,
        -1.34039121e-02,  1.53885661e-02, -7.22936168e-02,
         9.67835858e-02, -8.08119476e-02, -4.53452719e-03,
        -6.42011836e-02, -4.99278419e-02,  4.64197770e-02,
         2.21341308e-02,  3.13109234e-02,  9.13568661e-02,
        -4.61120047e-02, -1.02761127e-01,  3.04416418e-02,
         5.09876274e-02,  6.70140907e-02,  1.04042925e-02,
         1.63533408e-02,  3.92030738e-02,  2.17153989e-02,
         5.36603294e-02,  3.62809524e-02, -4.22140062e-02,
        -2.47227084e-02,  1.90312061e-02,  3.61724533e-02,
         6.37020841e-02, -3.21584102e-03, -8.50390922e-03,
         3.94655429e-02,  9.02655255e-03,  1.93095822e-02,
         6.60717934e-02,  1.02695180e-02, -4.43853624e-02,
        -1.56523529e-02, -1.55714555e-02,  1.32904705e-02,
        -1.16108228e-02,  4.21832167e-02, -5.44776618e-02,
         1.29237235e-01, -2.25756839e-02,  5.26204146e-02,
        -1.58436596e-02,  9.33165029e-02,  6.38026977e-03,
        -9.36163496e-03, -6.08875938e-02, -3.27308029e-02,
        -3.44816521e-02,  3.29973884e-02, -4.79392149e-02,
        -9.81300846e-02,  2.91164629e-02, -2.70903222e-02,
         1.81867033e-02, -1.73860490e-02, -4.40371633e-02,
        -7.97002092e-02,  3.01647466e-02, -6.35260865e-02,
         1.25963241e-02,  8.50249976e-02, -4.58910428e-02,
         5.81017323e-02, -2.71001942e-02,  8.42775702e-02,
        -4.09972817e-02, -3.37656029e-02,  1.02088144e-02,
        -2.54193172e-02, -1.40610306e-08,  4.94446829e-02,
        -9.04356614e-02, -6.06710389e-02,  8.29529613e-02,
        -3.29032615e-02,  4.14910279e-02,  9.99592058e-03,
         6.96136709e-03,  3.99230840e-03, -3.24333347e-02,
        -3.14657018e-02, -5.33161797e-02, -3.80913652e-02,
         1.62076838e-02,  2.45778169e-02, -7.26419911e-02,
        -6.56893700e-02, -8.23131725e-02, -8.00500736e-02,
        -5.36649376e-02,  5.60894758e-02, -1.10913441e-02,
         9.62202670e-04, -1.22690313e-01, -5.13836294e-02,
         9.96701699e-03,  1.00696459e-02,  1.07073106e-01,
         1.19758304e-02,  1.00423656e-02, -6.28261864e-02,
        -7.49697238e-02, -6.34075282e-03, -2.72201486e-02,
        -1.28096193e-01, -2.62459833e-02, -1.81464087e-02,
        -9.85360146e-02, -3.02990507e-02, -4.02614996e-02,
         9.94291157e-02,  5.35999909e-02,  2.74899807e-02,
        -5.53684495e-03,  8.43571126e-02,  8.35161954e-02,
         3.74305360e-02,  7.11937249e-02,  2.98903082e-02,
         2.32728776e-02, -3.62111889e-02,  6.20539710e-02,
         2.15148460e-02,  5.19732535e-02,  1.45337814e-02,
        -4.60966341e-02,  5.02554439e-02, -7.27027431e-02,
         2.92779319e-02,  5.62663078e-02, -3.86354811e-02,
         1.53831942e-02, -6.23094663e-02, -2.77466550e-02]], dtype=float32)

<h2>Clustering</h2>

In [36]:
from sklearn.cluster import DBSCAN
dbscan = DBSCAN(eps=0.2, min_samples=1, metric='cosine')
clusters=dbscan.fit_predict(embeddings)
clusters

array([0, 1, 2, ..., 0, 1, 7], shape=(2410,))

In [37]:
df['cluster']=clusters

In [45]:
df[df.cluster==1]

,timestamp,source,log_message,target_label,cluster
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,1
10,08-09-2025 18:58,ModernCRM,Email server encountered a sending fault,Error,1
217,1/22/2025 5:45,BillingSystem,Mail service encountered a delivery glitch,Error,1
248,05-02-2025 23:04,ModernHR,Service disruption caused by email sending error,Critical Error,1
265,3/30/2025 23:53,ModernCRM,Email system had a problem sending emails,Error,1
361,11/19/2025 23:06,BillingSystem,Email service experienced a sending issue,Error,1
450,10/27/2025 5:59,ThirdPartyAPI,Email delivery system encountered an error,Error,1
477,12-02-2025 10:30,AnalyticsEngine,Email transmission error caused service impact,Critical Error,1
570,11-07-2025 18:08,ThirdPartyAPI,Email service impacted by sending failure,Critical Error,1
678,4/28/2025 15:13,AnalyticsEngine,Email delivery problem affected system,Critical Error,1
695,6/30/2025 12:46,ThirdPartyAPI,Service outage due to email delivery problem,Critical Error,1
816,07-09-2025 09:38,BillingSystem,Error in email delivery affected service,Critical Error,1
926,2/17/2025 8:01,ModernCRM,Email service suffered a delivery failure,Error,1
1011,02-09-2025 17:04,AnalyticsEngine,Error in email sending impacted service,Critical Error,1
1018,2/16/2025 15:02,BillingSystem,Mail service impacted by delivery glitch,Critical Error,1
1046,11/26/2025 22:54,AnalyticsEngine,Email service had a difficulty delivering mess...,Error,1
1058,10/24/2025 5:37,AnalyticsEngine,Email system failed to deliver emails,Error,1
1082,5/17/2025 11:20,ModernHR,Delivery failure impacted email services,Critical Error,1
1151,6/17/2025 15:13,ThirdPartyAPI,Mail service was unable to send emails,Error,1
1176,10-01-2025 12:27,AnalyticsEngine,Email provider faced a delivery challenge,Error,1
1189,02-09-2025 06:15,ModernCRM,Service issue caused by email delivery error,Critical Error,1
1359,8/18/2025 15:58,ModernCRM,Email system down due to sending error,Critical Error,1
1414,6/22/2025 23:07,ModernCRM,Email system encountered a sending error,Error,1
1427,10/26/2025 20:25,ModernHR,Email provider had trouble sending emails,Error,1
1453,09-11-2025 01:18,BillingSystem,Mail delivery error impacted email service,Critical Error,1
1554,03-02-2025 09:21,ModernCRM,Email system had a difficulty sending messages,Error,1
1567,05-11-2025 11:17,ThirdPartyAPI,Email system affected by delivery failure,Critical Error,1
1582,09-10-2025 09:27,BillingSystem,Email delivery failure resulted in service issue,Critical Error,1
1860,6/26/2025 1:08,BillingSystem,Email provider experienced a mail delivery issue,Error,1
1867,10-06-2025 11:04,ModernCRM,Email service had a sending malfunction,Error,1
1901,9/22/2025 2:52,ThirdPartyAPI,Email service experienced a mail sending issue,Error,1
1972,03-12-2025 03:48,ThirdPartyAPI,Delivery issue with email service caused outage,Critical Error,1
2049,10-01-2025 22:07,AnalyticsEngine,Email server experienced a delivery problem,Error,1
2165,04-04-2025 16:11,ThirdPartyAPI,Email server had trouble transmitting emails,Error,1
2281,3/23/2025 20:12,ThirdPartyAPI,Mail delivery issue caused service disruption,Critical Error,1
2284,10-04-2025 18:15,BillingSystem,Email service down due to transmission issue,Critical Error,1
2312,03-09-2025 21:16,ModernHR,Email service faced a delivery obstacle,Error,1
2340,3/26/2025 8:10,ModernCRM,Service outage due to email transmission error,Critical Error,1
2408,11-11-2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,1

In [46]:
cluster_sizes = df['cluster'].value_counts()
large_clusters = cluster_sizes[cluster_sizes > 10].index.tolist()
for cluster_id in large_clusters:
    print(f"\n📌 Cluster {cluster_id} — {cluster_sizes[cluster_id]} log_messages\n")
    cluster_messages = df[df['cluster'] == cluster_id]['log_message'].head(5)
    for msg in cluster_messages:
        print(f"- {msg}")

📌 Cluster 0 — 1017 log_messages

- nova.osapi_compute.wsgi.server [req-b9718cd8-f65e-49cc-8349-6cf7122af137 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" status: 200 len: 1893 time: 0.2675118
- nova.osapi_compute.wsgi.server [req-4895c258-b2f8-488f-a2a3-4fae63982e48 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" HTTP status code -  200 len: 211 time: 0.0968180
- nova.osapi_compute.wsgi.server [req-ee8bc8ba-9265-4280-9215-dbe000a41209 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1874 time: 0.2280791
- nova.osapi_compute.wsgi.server [req-f0bffbc3-5ab0-4916-91c1-0a61dd7d4ec2 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" Return code: 200 len: 1874 time: 0.2131531
- nova.osapi_compute.wsgi.server [req-2bf7cfee-a236-42f3-8fb1-96fefab0b302 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1874 time: 0.1794369

📌 Cluster 5 — 147 log_messages

- nova.compute.claims [req-a07ac654-8e81-416d-bfbb-189116b07969 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: bf8c824d-f099-4433-a41e-e3da7578262e] Total memory: 64172 MB, used: 512.00 MB
- nova.compute.claims [req-d6986b54-3735-4a42-9074-0ba7d9717de9 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: af5f7392-f7d4-4298-b647-c98924c64aa1] memory limit: 96258.00 MB, free: 95746.00 MB
- nova.compute.claims [req-72b4858f-049e-49e1-b31e-b562c5018eaf 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 63a0d960-70b6-44c6-b606-491478a5cadf] disk limit not specified, defaulting to unlimited
- nova.compute.claims [req-5c8f52bd-8e3c-41f0-95a5-7861d247cafa 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: d96a117b-0193-4549-bdcc-63b917273d1d] vcpu limit not specified, defaulting to unlimited
- nova.compute.claims [req-d38f479d-9bb9-4276-9688-52607e8fd350 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 95960536-049b-41f6-9049-05fc479b6a7c] disk limit not specified, defaulting to unlimited

📌 Cluster 11 — 100 log_messages

- User User685 logged out.
- User User395 logged in.
- User User225 logged in.
- User User494 logged out.
- User User900 logged in.

📌 Cluster 13 — 86 log_messages

- Backup started at 2025-05-14 07:06:55.
- Backup started at 2025-02-15 20:00:19.
- Backup ended at 2025-08-08 13:06:23.
- Backup started at 2025-11-14 08:27:43.
- Backup started at 2025-12-09 10:19:11.

📌 Cluster 7 — 60 log_messages

- Multiple bad login attempts detected on user 8538 account
- Multiple login failures occurred on user 9052 account
- User 7153 made multiple incorrect login attempts
- User 8300 made multiple incorrect login attempts
- Multiple login failures were detected for user 6373

📌 Cluster 8 — 60 log_messages

- Backup completed successfully.
- Backup completed successfully.
- Backup completed successfully.
- Backup completed successfully.
- Backup completed successfully.

📌 Cluster 21 — 58 log_messages

- System updated to version 3.9.1.
- System updated to version 5.5.4.
- System updated to version 4.7.4.
- System updated to version 3.7.7.
- System updated to version 2.6.2.

📌 Cluster 3 — 57 log_messages

- Shard 6 replication task ended in failure
- Data replication task for shard 14 did not complete
- Data replication task failed for shard 17
- Replication of data to shard 14 failed
- Data replication task for shard 6 did not complete

📌 Cluster 4 — 53 log_messages

- File data_6169.csv uploaded successfully by user User953.
- File data_3847.csv uploaded successfully by user User175.
- File data_7366.csv uploaded successfully by user User282.
- File data_1206.csv uploaded successfully by user User359.
- File data_1503.csv uploaded successfully by user User151.

📌 Cluster 17 — 52 log_messages

- Denied access attempt on restricted account Account2682
- Unauthorized login attempt on protected account Account5030
- Account Account9437 blocked due to failed login
- Account Account7999 access denied due to login failure
- Invalid login attempt made on secured account Account7864

📌 Cluster 32 — 51 log_messages

- Disk cleanup completed successfully.
- Disk cleanup completed successfully.
- Disk cleanup completed successfully.
- Disk cleanup completed successfully.
- Disk cleanup completed successfully.

📌 Cluster 6 — 51 log_messages

- Critical system unit error: unit ID Component55
- System component malfunction: component ID Component79
- Critical system element is down: element ID Component96
- Essential system part malfunction: part ID Component6
- Failure occurred in critical system component: component ID Component92

📌 Cluster 16 — 48 log_messages

- System reboot initiated by user User243.
- System reboot initiated by user User471.
- System reboot initiated by user User216.
- System reboot initiated by user User639.
- System reboot initiated by user User819.

📌 Cluster 20 — 48 log_messages

- User 7662 tried to bypass API security measures
- User 2367 failed to provide valid API access credentials
- User 3569 made an unauthorized API request
- Unauthorized user 2968 tried to access restricted API
- User 2186 attempted to access API without proper authorization

📌 Cluster 9 — 44 log_messages

- Account with ID 5351 created by User634.
- Account with ID 7813 created by User373.
- Account with ID 9827 created by User965.
- Account with ID 2520 created by User546.
- Account with ID 2300 created by User964.

📌 Cluster 1 — 39 log_messages

- Email service experiencing issues with sending
- Email server encountered a sending fault
- Mail service encountered a delivery glitch
- Service disruption caused by email sending error
- Email system had a problem sending emails

📌 Cluster 10 — 30 log_messages

- nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=512MB phys_disk=15GB used_disk=0GB total_vcpus=16 used_vcpus=0 pci_stats=[]
- nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
- nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Total usable vcpus: 16, total allocated vcpus: 0
- nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
- nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]

📌 Cluster 34 — 25 log_messages

- Abnormal behavior found on server 10, possible security threat
- Security alert: suspicious activity on server 1
- Anomalous activity identified on server 23, security review recommended
- Server 27 experienced potential security incident, review required
- Server 36 experienced potential security incident, review required

📌 Cluster 14 — 20 log_messages

- Detection of multiple disk faults in RAID setup
- RAID array suffered multiple hard drive failures
- RAID array experienced multiple disk crashes
- Multiple hard drive issues in RAID configuration found
- Identification of multiple faulty disks in RAID array

📌 Cluster 53 — 20 log_messages

- Module X experienced an invalid data format issue
- Input format mismatch occurred in module X
- Module X reported an error in input format validation
- Module X failed to process input due to formatting error
- Input data format in module X was invalid or corrupted

📌 Cluster 52 — 20 log_messages

- Service health check was not successful because of SSL certificate validation failures.
- Invalid SSL certificate resulted in a failed service health check.
- Service health check failure was due to an invalid or improperly configured SSL certificate.
- An issue with the SSL certificate caused the service health check to fail.
- Service health check failure was caused by an expired SSL certificate.

📌 Cluster 18 — 17 log_messages

- Boot process terminated unexpectedly due to kernel issue
- System encountered kernel panic during initialization phase
- Boot process was stopped by kernel malfunction
- System encountered kernel failure during bootup sequence
- Boot sequence failed due to kernel panic

📌 Cluster 25 — 13 log_messages

- System configuration is no longer valid
- Configuration is corrupted throughout the system
- Cross-system configuration failure occurred
- System configuration is experiencing errors
- Configuration malfunction is system-wide

📌 Cluster 42 — 13 log_messages

- User 5127 has escalated admin privileges without authorization
- User 9745 has escalated to admin level
- User 8483 escalated privileges to admin level
- User 1987 has escalated to admin level
- User 8395 escalated privileges to admin level

📌 Cluster 59 — 12 log_messages

- Potential security threat: Admin privilege escalation for user 5130
- Admin privilege escalation alert for user 2893
- Admin privilege escalation alert for user 8532
- Potential security threat: Admin privilege escalation for user 1554
- Warning: Potential admin privilege escalation for user 5720

📌 Cluster 26 — 11 log_messages

- Privilege elevation detected for user 5038
- Elevation of admin privileges detected for user 6137
- Elevation of admin privileges detected for user 4907
- User 6069 has been granted elevated admin privileges
- Admin privilege elevation warning for user 7574

In [76]:
import re
def classify_with_regex(log_message):
    regex_patterns={
        r"User User\d+ logged (out|in)":"User Action",
        r"Backup (started|ended) at .*":"System Notification",
        r"Backup completed successfully.":"System Notification",
        r"System updated to version .*":"System Notification",
        r"File .* uploaded successfully by user .*":"System Notification",
        r"Disk cleanup completed successfully.":"System Notification",
        r"System reboot initiated by user .*":"System Notification",
        r"Account with ID .* created by .*":"User Action"
    }
    for pattern, label in regex_patterns.items():
        if re.search(pattern, log_message,flags=re.IGNORECASE):
            return label
    return None

In [77]:
classify_with_regex("Account with ID 5351 created by User634.")

'User Action'

In [78]:
df['regex_label'] = df['log_message'].apply(classify_with_regex)

In [86]:
df[df.regex_label.notnull()].info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, 7 to 2403
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   timestamp     500 non-null    object
 1   source        500 non-null    object
 2   log_message   500 non-null    object
 3   target_label  500 non-null    object
 4   cluster       500 non-null    int64
 5   regex_label   500 non-null    object
dtypes: int64(1), object(5)
memory usage: 27.3+ KB

<h2>Non Regex</h2>

In [90]:
df_non_regex=df[df.regex_label.isna()].copy()
df_non_regex

,timestamp,source,log_message,target_label,cluster,regex_label
0,27-06-2025 07:20,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,0,None
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,1,None
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,2,None
3,12-07-2025 00:24,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,0,None
4,02-06-2025 18:25,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,0,None
...,...,...,...,...,...,...
2405,13-08-2025 07:29,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,0,None
2406,01-11-2025 05:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,7,None
2407,03-08-2025 03:07,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,0,None
2408,11-11-2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,1,None
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,7,None

In [97]:
label_counts = df_non_regex['target_label'].value_counts()
rare_labels = label_counts[label_counts < 5].index
df_non_regex[df_non_regex['target_label'].isin(rare_labels)] #only LegacyCRM source, use LLM classification, rest use bert

,timestamp,source,log_message,target_label,cluster,regex_label
60,06-10-2025 16:55,LegacyCRM,Lead conversion failed for prospect ID 7842 du...,Workflow Error,24,None
255,03-05-2025 16:55,LegacyCRM,API endpoint 'getCustomerDetails' is deprecate...,Deprecation Warning,48,None
377,24-06-2025 12:16,LegacyCRM,Customer follow-up process for lead ID 5621 fa...,Workflow Error,62,None
1325,17-04-2025 07:33,LegacyCRM,Escalation rule execution failed for ticket ID...,Workflow Error,105,None
1734,30-04-2025 07:47,LegacyCRM,The 'ExportToCSV' feature is outdated. Please ...,Deprecation Warning,118,None
1826,23-01-2025 10:33,LegacyCRM,Support for legacy authentication methods will...,Deprecation Warning,122,None
2217,12-05-2025 09:46,LegacyCRM,Task assignment for TeamID 3425 could not comp...,Workflow Error,133,None

In [98]:
df_non_legacy=df_non_regex[df_non_regex['source']!="LegacyCRM"]
df_non_legacy.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI'], dtype=object)

In [99]:
filtered_embeddings = model.encode(df_non_legacy["log_message"].tolist())
filtered_embeddings[:2]

array([[-1.02939621e-01,  3.35459411e-02, -2.20260732e-02,
         1.55101740e-03, -9.86917876e-03, -1.78956270e-01,
        -6.34409785e-02, -6.01761639e-02,  2.81109158e-02,
         5.99620491e-02, -1.72618348e-02,  1.43363548e-03,
        -1.49560034e-01,  3.15287686e-03, -5.66030927e-02,
         2.71685235e-02, -1.49891041e-02, -3.54037657e-02,
        -3.62936445e-02, -1.45410765e-02, -5.61491773e-03,
         8.75539035e-02,  4.55120578e-02,  2.50963885e-02,
         1.00187510e-02,  1.24267349e-02, -1.39923573e-01,
         7.68696293e-02,  3.14095505e-02, -4.15247958e-03,
         4.36902344e-02,  1.71250012e-02, -8.00951198e-02,
         5.74006326e-02,  1.89091656e-02,  8.55262503e-02,
         3.96398641e-02, -1.34371817e-01, -1.44360063e-03,
         3.06704035e-03,  1.76854044e-01,  4.44885530e-03,
        -1.69274509e-02,  2.24266481e-02, -4.35049310e-02,
         6.09034160e-03, -9.98169929e-03, -6.23972900e-02,
         1.07372422e-02, -6.04895083e-03, -7.14660808e-02,
        -8.45799781e-03, -3.18019874e-02, -1.00518376e-01,
         2.25873096e-04, -1.89341009e-02, -3.17793973e-02,
         4.00860943e-02,  2.19178163e-02, -2.59528961e-02,
         5.84525056e-02, -8.12509581e-02,  2.12029163e-02,
        -5.02687655e-02,  1.32057499e-02,  1.32675481e-03,
         2.27062907e-02, -3.45793478e-02,  3.91546972e-02,
        -2.09433399e-02,  3.24829482e-03,  4.43961099e-02,
        -9.85357612e-02, -2.88895369e-02, -6.85023936e-03,
         5.38818911e-02,  6.46110177e-02, -2.45060585e-02,
         9.21828747e-02, -7.49868751e-02,  1.23994909e-02,
        -1.00026578e-01, -4.64910977e-02,  6.01570047e-02,
        -2.46480722e-02, -7.08076209e-02, -2.77270824e-02,
         9.72611383e-02,  3.85841392e-02, -1.44293057e-02,
        -7.46909878e-04, -1.04304878e-02, -1.61842871e-02,
         4.43628095e-02,  9.25995968e-03,  7.14165792e-02,
         6.37917742e-02,  4.94931564e-02, -6.02567680e-02,
         4.04805690e-02, -3.42860855e-02, -1.93881039e-02,
         6.61233589e-02,  6.01589568e-02,  1.09371776e-02,
        -5.38631296e-03,  1.44579662e-02,  9.25429910e-02,
        -3.14564183e-02, -1.84352025e-02,  9.91876610e-03,
        -1.85574219e-02,  1.31284434e-03,  2.26702014e-05,
         2.02741218e-03,  2.75256746e-02, -4.81928065e-02,
         5.42826168e-02, -7.32066929e-02,  4.88667302e-02,
         4.98490408e-02, -9.01139528e-03, -4.68905792e-02,
        -4.25887071e-02, -8.19523931e-02,  3.87106128e-02,
         7.85504058e-02,  1.46077081e-32,  1.66706275e-02,
         5.25494143e-02, -1.82448905e-02, -1.26686739e-02,
         6.52837083e-02, -2.11777352e-02, -4.06323038e-02,
         4.14947495e-02, -2.48360801e-02, -1.33068245e-02,
        -5.46753556e-02, -5.99200139e-04, -4.89246612e-03,
        -6.27359450e-02, -3.84878367e-02, -6.13543652e-02,
         8.27405825e-02,  2.34379973e-02, -8.63091834e-03,
         1.31003130e-02,  6.44215122e-02, -4.41361926e-02,
        -6.98633417e-02, -7.36059994e-02, -4.33264039e-02,
         6.96522417e-03, -5.05956709e-02, -1.60911996e-02,
        -5.66794015e-02,  3.35454731e-03,  5.34115247e-02,
         2.47761514e-02, -1.47986487e-02, -2.93242969e-02,
         7.30228499e-02, -1.86833944e-02,  8.13137367e-02,
        -2.69967224e-02, -5.68056367e-02, -6.59389049e-02,
        -5.95394848e-03,  2.85312776e-02, -7.85358176e-02,
        -2.76694540e-03, -3.26469471e-03, -9.28332806e-02,
        -7.27363005e-02, -3.31903026e-02,  1.01411112e-01,
         9.79882479e-02, -9.78740230e-02,  1.98667571e-02,
         2.38837320e-02, -1.81672648e-02, -3.73708978e-02,
         1.96551997e-03,  6.34425730e-02,  1.18271559e-02,
        -1.12041300e-02, -3.87316644e-02,  9.32424441e-02,
         4.26628767e-03, -1.66872628e-02, -6.87464401e-02,
         1.55119859e-02, -4.97755483e-02,  3.34493034e-02,
         8.00032541e-02,  2.12282464e-02,  1.34581864e-01,
        -2.30729766e-02,  5.53858802e-02,  3.07558421e-02,
        -2.93905940e-02,  2.31905375e-02, -9.34307799e-02,
         7.58034959e-02, -5.21208439e-03, -5.14523312e-02,
         3.32688726e-02,  3.67963351e-02, -1.06450235e-02,
         1.01634776e-02, -2.07651369e-02, -5.85519075e-02,
         4.79328595e-02,  2.13694703e-02,  8.76213461e-02,
         3.35494406e-03, -3.80336568e-02, -1.81205384e-02,
         6.87449984e-03,  5.15880026e-02, -4.75598909e-02,
        -6.12065606e-02, -1.45483574e-32,  4.12801234e-03,
         4.59641684e-03, -5.63900359e-02,  4.32465039e-03,
        -1.09439227e-03,  9.31954943e-03, -2.20269002e-02,
         5.79564497e-02, -1.44787477e-02,  4.64155786e-02,
         1.43542871e-01, -6.89756870e-02,  6.09631799e-02,
        -8.93743932e-02,  2.40919460e-02,  2.06010658e-02,
        -2.82415487e-02, -6.48315251e-02,  5.64795695e-02,
        -7.48336036e-03, -3.52058038e-02,  8.51060525e-02,
         1.30359633e-02,  2.02257764e-02, -1.44390641e-02,
        -4.63718511e-02,  1.77209619e-02,  1.59105826e-02,
        -9.51009318e-02, -3.54526863e-02,  2.08696295e-02,
         3.84389190e-03, -8.77918154e-02,  6.44575655e-02,
         1.44171156e-02,  3.84733523e-03,  4.70991470e-02,
         4.94661182e-02,  1.53862564e-02, -2.59578805e-02,
         9.10894647e-02,  1.83307882e-02, -5.89206666e-02,
         2.51992680e-02, -3.30374353e-02,  8.23345333e-02,
         1.74792372e-02,  6.48047701e-02, -1.19674122e-02,
        -3.31778415e-02,  3.00177671e-02,  3.54220010e-02,
        -1.39624272e-02,  6.69272467e-02,  3.87919769e-02,
         6.06916696e-02,  1.17958151e-03, -2.38787029e-02,
        -1.26930416e-01,  1.13846380e-02,  1.59290042e-02,
        -1.29427500e-02, -8.63247886e-02,  8.53661261e-03,
         6.03761226e-02,  1.51121775e-02, -1.19132362e-01,
         1.15234600e-02,  5.97089604e-02, -3.93345878e-02,
         1.55673325e-02,  1.04602240e-02, -4.72456925e-02,
        -2.59243399e-02,  9.98525601e-03,  3.07146404e-02,
        -7.14844763e-02,  6.98965415e-03, -1.55133577e-02,
         2.18864139e-02, -2.78145913e-02,  6.92733005e-02,
        -2.75903586e-02,  2.62429845e-02,  3.52561660e-02,
        -4.26419862e-02,  7.46284146e-04,  6.59866631e-02,
        -5.15105948e-02, -3.58434319e-02, -6.53440924e-03,
        -2.75858175e-02, -1.00125581e-01,  7.83326104e-02,
        -1.45798642e-02, -6.18457250e-08,  2.00325698e-02,
         6.59784526e-02, -2.04702560e-02,  1.64043903e-02,
         7.63001442e-02,  7.32182562e-02,  5.65784518e-03,
        -6.97782438e-04, -3.63794621e-03,  6.02393858e-02,
        -3.27187181e-02, -6.45838156e-02, -5.97952493e-02,
        -1.76696330e-02,  6.10143691e-03, -5.63488016e-03,
        -1.22972250e-01,  6.35818988e-02, -2.19432022e-02,
        -1.16406500e-01,  2.34366246e-02, -7.23525658e-02,
         2.31773835e-02, -6.55987561e-02, -7.42682368e-02,
         2.60146223e-02,  3.59758623e-02,  7.68432692e-02,
        -3.08057331e-02, -2.34794039e-02, -6.30426034e-02,
        -3.62158157e-02, -1.03560016e-02, -4.75602485e-02,
        -2.87522227e-02,  2.96400599e-02, -5.26892208e-03,
         5.67889623e-02, -3.74485948e-03,  3.09612993e-02,
         3.48226950e-02,  3.78607921e-02,  2.10155267e-02,
         2.70691738e-02,  5.25520407e-02,  7.16229230e-02,
        -5.53755183e-03,  4.01093923e-02,  5.16276695e-02,
        -2.67314408e-02,  5.94224073e-02, -4.29224260e-02,
        -1.19760446e-02,  3.05984747e-02, -7.40331411e-02,
         1.84222143e-02, -8.64861440e-03, -8.83557573e-02,
        -5.91984391e-02, -1.00920675e-04,  1.12913631e-01,
         4.57792636e-03, -4.25971746e-02,  3.22620897e-03],
       [ 8.04571714e-03, -3.57392281e-02,  4.93873917e-02,
        -7.19184149e-03,  6.17644750e-04, -9.05685052e-02,
         5.75594865e-02, -4.39446270e-02,  1.74751636e-02,
         5.21203242e-02, -4.62332033e-02,  2.49039363e-02,
         4.80811782e-02,  6.86636567e-02,  3.56146656e-02,
         3.00089642e-02,  2.61449497e-02, -9.05241296e-02,
        -8.02173615e-02,  5.04851192e-02, -7.90870488e-02,
        -1.76855002e-03, -2.48927530e-02,  9.02152434e-02,
         5.83698181e-03, -6.91070855e-02, -6.67966083e-02,
        -6.99113635e-03, -1.04565986e-01, -2.66473852e-02,
         3.05640064e-02,  2.02934369e-02,  2.25454886e-02,
        -4.22687922e-03,  1.11173484e-02,  6.78260773e-02,
         1.06073590e-02,  7.56636113e-02, -8.22777823e-02,
         8.45735706e-03, -6.97612464e-02, -4.21974584e-02,
        -1.05674397e-02,  2.23673340e-02,  5.64496815e-02,
         8.16500373e-03,  1.09344080e-01,  3.16564441e-02,
        -1.76923554e-02, -3.21071148e-02, -3.39975841e-02,
        -4.91802581e-04,  3.72874690e-03,  2.83771455e-02,
        -1.28521984e-02, -1.07933208e-03, -6.32418916e-02,
         6.89900741e-02,  1.77270379e-02, -5.20960055e-02,
         8.28307122e-03,  5.45032695e-02, -5.42099662e-02,
        -4.53333110e-02, -4.07494120e-02, -2.82698181e-02,
         1.23605840e-02, -2.13816017e-02, -2.36265361e-02,
         1.25317592e-02, -2.37170625e-02,  3.97411808e-02,
        -1.24362275e-01,  7.60625228e-02,  5.50834052e-02,
         8.28216746e-02,  2.97118574e-02, -1.84067208e-02,
        -1.96194761e-02,  5.54319136e-02, -3.49144414e-02,
        -4.14678007e-02, -3.37047353e-02,  7.31324479e-02,
         4.41836640e-02,  2.55246740e-02, -8.26408435e-03,
        -1.07322847e-02, -4.26243879e-02, -2.84964102e-03,
         7.38559514e-02,  2.27767937e-02,  7.15389557e-04,
         4.36012261e-02,  5.09079471e-02,  6.38482645e-02,
        -2.73155570e-02, -6.55021369e-02, -7.69265294e-02,
         3.55171151e-02,  9.60493386e-02,  2.18195524e-02,
         1.20154712e-02, -1.17863379e-02, -4.57923161e-03,
        -8.58035590e-03,  3.37150730e-02,  2.31918134e-02,
        -7.58325532e-02, -5.23879267e-02,  4.53934073e-02,
        -3.80785577e-02, -3.34904976e-02,  9.20353308e-02,
         2.87688691e-02, -3.33816931e-02, -1.95852900e-03,
        -3.04580055e-04, -1.70499235e-02,  2.85335984e-02,
        -8.81096572e-02, -4.02253456e-02, -4.00093347e-02,
        -1.03193149e-02, -2.51968466e-02,  2.14093029e-02,
         1.31045237e-01, -5.29632801e-34, -1.09651692e-01,
         1.29811568e-02,  5.92657691e-03,  4.73506227e-02,
        -8.60296935e-03, -3.67089324e-02,  3.05215158e-02,
         5.53066693e-02, -4.71985638e-02, -1.25118727e-02,
        -1.15366414e-01,  9.07998811e-03,  1.07346505e-01,
        -4.94734831e-02, -1.34290671e-02, -4.61562574e-02,
         2.45320704e-02,  9.45076440e-03,  2.04324219e-02,
        -3.99919078e-02, -4.67826128e-02,  2.21171696e-02,
        -4.58187200e-02, -8.13272968e-03, -7.65670184e-03,
         1.92284547e-02,  4.85845432e-02, -2.55903210e-02,
         1.61540357e-03, -1.37180369e-02,  9.67309345e-03,
         7.36417389e-03,  1.14088319e-02,  1.28853440e-01,
         7.71836052e-03,  7.06362650e-02,  2.54452135e-02,
         4.06523943e-02,  2.44039707e-02,  1.43777113e-02,
        -6.00932501e-02,  7.38180280e-02, -2.44701020e-02,
         8.98901448e-02,  3.17055243e-03,  1.01834454e-01,
         4.17742133e-02, -5.95177487e-02, -3.23181786e-02,
         3.80938761e-02,  1.21155363e-02, -4.07834165e-02,
         2.84823403e-02,  4.90988754e-02, -9.35704913e-03,
         6.50074109e-02,  7.23532140e-02, -1.67793669e-02,
        -8.22419021e-03, -1.61573216e-02,  5.96225485e-02,
        -3.36083770e-02,  2.12108567e-02, -6.06090687e-02,
         1.54377669e-01, -7.24146292e-02, -3.77272554e-02,
        -3.26890312e-02, -1.80383236e-03, -1.01960171e-02,
        -1.60677219e-03, -6.91846609e-02,  8.28444809e-02,
         9.88839418e-02,  3.45466356e-03, -9.90247875e-02,
        -3.52826901e-02, -7.13178515e-02, -4.96000238e-02,
        -3.43954526e-02, -8.13042149e-02,  4.81448062e-02,
         5.00683207e-03, -2.21499726e-02, -5.60056977e-02,
         1.00067444e-02, -3.59794199e-02,  1.06184311e-01,
        -4.54196744e-02,  7.16393143e-02, -2.36773062e-02,
         9.98143200e-03,  2.73602195e-02,  1.05985463e-01,
         4.60163429e-02,  9.59029178e-34, -1.12306982e-01,
         2.78912336e-02, -3.35900635e-02,  5.39242551e-02,
        -2.22291443e-02,  1.53769050e-02,  3.10411565e-02,
         3.39011066e-02,  7.43167326e-02,  3.42471153e-02,
        -3.35047860e-03, -2.05350518e-02, -3.62370051e-02,
         2.29334142e-02, -3.01992167e-02, -1.00819930e-01,
         3.29193994e-02,  6.77542835e-02,  1.35645578e-02,
        -5.20545896e-03, -6.58158809e-02,  9.54550654e-02,
        -1.34039121e-02,  1.53885661e-02, -7.22936168e-02,
         9.67835858e-02, -8.08119476e-02, -4.53452719e-03,
        -6.42011836e-02, -4.99278419e-02,  4.64197770e-02,
         2.21341308e-02,  3.13109234e-02,  9.13568661e-02,
        -4.61120047e-02, -1.02761127e-01,  3.04416418e-02,
         5.09876274e-02,  6.70140907e-02,  1.04042925e-02,
         1.63533408e-02,  3.92030738e-02,  2.17153989e-02,
         5.36603294e-02,  3.62809524e-02, -4.22140062e-02,
        -2.47227084e-02,  1.90312061e-02,  3.61724533e-02,
         6.37020841e-02, -3.21584102e-03, -8.50390922e-03,
         3.94655429e-02,  9.02655255e-03,  1.93095822e-02,
         6.60717934e-02,  1.02695180e-02, -4.43853624e-02,
        -1.56523529e-02, -1.55714555e-02,  1.32904705e-02,
        -1.16108228e-02,  4.21832167e-02, -5.44776618e-02,
         1.29237235e-01, -2.25756839e-02,  5.26204146e-02,
        -1.58436596e-02,  9.33165029e-02,  6.38026977e-03,
        -9.36163496e-03, -6.08875938e-02, -3.27308029e-02,
        -3.44816521e-02,  3.29973884e-02, -4.79392149e-02,
        -9.81300846e-02,  2.91164629e-02, -2.70903222e-02,
         1.81867033e-02, -1.73860490e-02, -4.40371633e-02,
        -7.97002092e-02,  3.01647466e-02, -6.35260865e-02,
         1.25963241e-02,  8.50249976e-02, -4.58910428e-02,
         5.81017323e-02, -2.71001942e-02,  8.42775702e-02,
        -4.09972817e-02, -3.37656029e-02,  1.02088144e-02,
        -2.54193172e-02, -1.40610306e-08,  4.94446829e-02,
        -9.04356614e-02, -6.06710389e-02,  8.29529613e-02,
        -3.29032615e-02,  4.14910279e-02,  9.99592058e-03,
         6.96136709e-03,  3.99230840e-03, -3.24333347e-02,
        -3.14657018e-02, -5.33161797e-02, -3.80913652e-02,
         1.62076838e-02,  2.45778169e-02, -7.26419911e-02,
        -6.56893700e-02, -8.23131725e-02, -8.00500736e-02,
        -5.36649376e-02,  5.60894758e-02, -1.10913441e-02,
         9.62202670e-04, -1.22690313e-01, -5.13836294e-02,
         9.96701699e-03,  1.00696459e-02,  1.07073106e-01,
         1.19758304e-02,  1.00423656e-02, -6.28261864e-02,
        -7.49697238e-02, -6.34075282e-03, -2.72201486e-02,
        -1.28096193e-01, -2.62459833e-02, -1.81464087e-02,
        -9.85360146e-02, -3.02990507e-02, -4.02614996e-02,
         9.94291157e-02,  5.35999909e-02,  2.74899807e-02,
        -5.53684495e-03,  8.43571126e-02,  8.35161954e-02,
         3.74305360e-02,  7.11937249e-02,  2.98903082e-02,
         2.32728776e-02, -3.62111889e-02,  6.20539710e-02,
         2.15148460e-02,  5.19732535e-02,  1.45337814e-02,
        -4.60966341e-02,  5.02554439e-02, -7.27027431e-02,
         2.92779319e-02,  5.62663078e-02, -3.86354811e-02,
         1.53831942e-02, -6.23094663e-02, -2.77466550e-02]], dtype=float32)

In [103]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

X = filtered_embeddings
y = df_non_legacy['target_label'].tolist() 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

clf = LogisticRegression(max_iter=1000)  
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.989501312335958

Classification Report:
                 precision    recall  f1-score   support

Critical Error       0.92      1.00      0.96        35
         Error       0.96      0.89      0.92        27
   HTTP Status       1.00      1.00      1.00       197
Resource Usage       1.00      1.00      1.00        35
Security Alert       1.00      0.99      0.99        87

      accuracy                           0.99       381
     macro avg       0.98      0.98      0.98       381
  weighted avg       0.99      0.99      0.99       381

In [106]:
np.column_stack((y_test, y_pred))[0:5]

array([['Security Alert', 'Security Alert'],
       ['Resource Usage', 'Resource Usage'],
       ['HTTP Status', 'HTTP Status'],
       ['HTTP Status', 'HTTP Status'],
       ['HTTP Status', 'HTTP Status']], dtype='<U14')

In [105]:
import joblib

joblib.dump(clf, '../models/log_classifier.joblib')

['models/log_classifier.joblib']

In [108]:
df.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI', 'LegacyCRM'], dtype=object)